<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search buildings
    </h1>

        <?php echo $this->tag->linkTo(["/", "Home"]) ?> |
        <?php echo $this->tag->linkTo(["buildings/new", "Create building"]) ?>

</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "buildings/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">ID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStreetId" class="col-sm-2 control-label">Street ID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["street_id", "type" => "number", "class" => "form-control", "id" => "fieldStreetId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStreetId" class="col-sm-2 control-label">Street title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(array("street_id",
            Streets::find(),
            "useEmpty" => true,
            "emptyText" => "Please select",
            "using" => array("id", "title"),
        ));
        ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNumber" class="col-sm-2 control-label">Number</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["number", "type" => "number", "class" => "form-control", "id" => "fieldNumber"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
