<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["buildings", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create building
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    [
        "buildings/create",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<!--<div class="form-group">-->
<!--    <label for="fieldStreetId" class="col-sm-2 control-label">Street</label>-->
<!--    <div class="col-sm-10">-->
<!--        --><?php //echo $this->tag->textField(["street_id", "type" => "number", "class" => "form-control", "id" => "fieldStreetId"]) ?>
<!--    </div>-->
<!--</div>-->

<div class="form-group">
    <label for="fieldStreetId" class="col-sm-2 control-label">Street title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(array("street_id",
            Streets::find(),
            "useEmpty" => true,
            "emptyText" => "Please select",
            "using" => array("id", "title"),
        ));
        ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Building title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNumber" class="col-sm-2 control-label">Building number</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["number", "type" => "number", "class" => "form-control", "id" => "fieldNumber"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
