<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["buildings/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["buildings/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Street ID</th>
            <th>Street title</th>
            <th>Title</th>
            <th>Number</th>

            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $building): ?>
            <tr>
                <td><?php echo $building->id ?></td>
                <td><?php echo $building->street_id ?></td>
                <td><?php echo $building->streets->title ?></td>
                <td><?php echo $building->title ?></td>
                <td><?php echo $building->number ?></td>

                <td><?php echo $this->tag->linkTo(["buildings/edit/" . $building->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["buildings/delete/" . $building->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("buildings/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("buildings/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("buildings/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("buildings/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
