<?php

use Phalcon\DI;

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["streets/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["streets/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Total buildings</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $street): ?>
            <tr>
                <td><?php echo $street->id ?></td>
                <td><?php echo $street->title ?></td>
                <td><?php echo DI::getDefault()->get('total')->getTotal($street->id); ?></td> <!-- Получаем данные из сервиса Total.php -->
                <td><?php echo $this->tag->linkTo(["streets/edit/" . $street->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["streets/delete/" . $street->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php

foreach ($st as $s) {
    echo $s->name, "\n";
}

?>
<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("streets/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("streets/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("streets/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("streets/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
